### ISSUE TITLE
Incorrect bottom margin when loading

### ISSUE THREAD

**Issue by juanpujol** [Beakyn/aurelia-choices#2]
The bottom margin of the select is bigger while loading, but it get's back to normal when the choices select is complete loaded.

![bug-bottom-margin-when-loading](https://cloud.githubusercontent.com/assets/30832/22370025/5c0fbcb2-e476-11e6-80e3-fc6d5db158d9.gif)

Could you verify the template?

Thanks.

**Comment by juanpujol** [comment]
Just tested this and the problem persists. Here's a new GIF.

![bug-bottom-margin-when-loading-2](https://cloud.githubusercontent.com/assets/30832/22393336/83d47b64-e4eb-11e6-8379-77cdcf5cb315.gif)

BTW, just updated the master branch with a bunch of code refactor, so don't forget to merge.

Thank you.

**Comment by riconegri** [comment]
I think now it's ok, css visually equal the normal select..., almost

**Comment by juanpujol** [comment]
@riconegri Didn't work. ran `npm install aurelia-choices` to be sure, but now I get this error:

![screenshot 2017-01-28 02 06 42](https://cloud.githubusercontent.com/assets/30832/22394150/fc8f2eec-e4fe-11e6-8b6a-e92fd61d11c8.jpg)

Please take a look tomorrow. I can't test the other issue because I can't access the Permissions page anymore.

Thank you.

**Comment by juanpujol** [comment]
Never mind, I just removed this tag `<require from="aurelia-choices/index"></require>` and it worked.

About the CSS, I'll like you to restore the visual to what it was. With the bottom-padding fixed.

I think it looks great like you did it, more similar to the other selects. But we're working on a plugin and any customization related to our app should be done outside the plugin. Maybe on the common UI theme.

For now, just fix the padding but make it like it was before.

Thanks.

**Comment by riconegri** [comment]
Last commit fix colors, format, loading text and placeholder at 'dev' branch
