### ISSUE TITLE
What's the .gitkeep file?

### ISSUE THREAD

**Issue by juanpujol** [Beakyn/aurelia-choices#4]
![screenshot 2017-01-27 10 25 17](https://cloud.githubusercontent.com/assets/30832/22370906/0e6135cc-e47b-11e6-9ad8-d1fbab62d9a7.jpg)

**Comment by riconegri** [comment]
Dirt from the old repository, dev now this file has gone

**Comment by juanpujol** [comment]
Thank you. Closing the issue.
